### PR TITLE
GS signalgen card and autogenerated javadocs under the docs folder

### PR DESCRIPTION
**Pull request by AhmetCanSolak**
This huge PR has 2 commits:
- GS card device commit, this one is not fully working. Will be tagging an issue and solve it.
- Autogenerated javadocs, since `java8-doclint` practices are not followed ignored them to generate docs, will be careful with future javadoc strings.

Please provide comment/review. Thanks.

### CODE REVIEW

**Comment by royerloic** [comment]
Please eventually test on the scope by switching the signal generator to GS, and switching cables too...

**Comment by AhmetCanSolak** [comment]
will be doing that soon too. Please approve if all okay for you

**Comment by haesleinhuepf** [comment]
Hey @AhmetCanSolak 

I would suggest putting auto-generated files not on github. At least not in the source-code repository. How about a separate docs repository? 

Regarding the GS thingy: I would suggest not putting anything on the master branch which is known to be not functional. Furthermore, it's hard to review this pull-request as there were 7000 files changed...

Last but not least, we Dresdeners don't work on the master-branch. So feel free to go ahead. My words are just well-meaning comments ;-)

Cheers,
Robert

**Comment by AhmetCanSolak** [comment]
Hi @haesleinhuepf sorry for super-late reply :(  

> I would suggest putting auto-generated files not on github. At least not in the source-code repository. How about a separate docs repository?

I agree with your suggestion. I have a separate docs repo already, will be populating that and migrating into ClearControl namespace. I will close this PR without merging.

> Last but not least, we Dresdeners don't work on the master-branch. So feel free to go ahead. My words are just well-meaning comments ;-)

I know thank you :)

**Pull request closed without merging**
