### PR TITLE
Folder name change from device to vendors to prevent confusion

### PR DESCRIPTION
**Pull request by AhmetCanSolak**
I am here proposing to change folder name "devices" under the all devices sub-folders to prevent any confusion as we alsa have "devices" folder one upper level. Please review the change and let me know if it may cause to any problem.

### CODE REVIEW

**Comment by haesleinhuepf** [comment]
Hi @AhmetCanSolak ,

refactoring and cleaning up is in general a very good idea. However, just my two cents on this: there are approximately 20 repositories depending on this one. So adapting code upstream may be a pain... If it's not absolutely necessary, I would vote for keeping the folder structure as it is.

Cheers,
Robert

**Comment by AhmetCanSolak** [comment]
Thank you for your comment @haesleinhuepf . Do you know how can I track the dependencies and understand the possible effects of such change?

Best,
Ahmet Can

**Comment by haesleinhuepf** [comment]
Unfortunately, you cannot track depend**ing** repositories upstream. Theoretically, anybody could have built something depending on clearcontrol. I think practically, it's just @royerloic , @adibrov , me and 2-3 more people. You may have a look at these depend**ing** repositories:

https://github.com/ClearControl/clearclij
https://github.com/ClearControl/clearcontrol-lightsheet
https://github.com/ClearControl/XWing
https://github.com/ClearControl/BScope
https://github.com/ClearControl/EasyScopy

**Comment by AhmetCanSolak** [comment]
I guess we do not have time to handle such fundamental refactoring by now.
@haesleinhuepf @royerloic i will close this pull request to keep here cleaner. fyi.

**Pull request closed without merging**
