### PR TITLE
Adding sqeazy support

### PR DESCRIPTION
**Pull request by psteinb**
The write speed to disk is not there yet (sqeazy 9MB/s) in comparison to RawFileSink (150 MB/s). This could have multiple reasons:
- sqeazy is running in single threaded mode (I need to update the API for this)
- during the writing/reading of compressed/uncompressed data I need to do a lot of memory allocations
- I am not using NIO correctly

### CODE REVIEW

**Comment by psteinb** [comment]
one more thing: reading into a fragmented memory region is unsupported for now, I need to figure out how to do this

**Comment by royerloic** [comment]
Great! The performance issues can be ironed out, I have noticed some things that can be fixed...

**Comment by psteinb** [comment]
thanks, I'd be curious of your findings. You know these APIs better than me, so I can only learn.

**Comment by royerloic** [comment]
Hi Peter, 

I have made some corrections (still on my machine) which should speed things up. As soon as I am back at my desk I push it. Note: no need to worry about the fragmented memory, its just a view. Unfortunately, I could not test these changes, sqy crashes on my machine (also before changing anything). Please wait for my changes before attempting a fix. Otherwise, looking good!! :-)

**Comment by psteinb** [comment]
thanks for the feedback. on my macOS test machine, gradle runs the 
clearcontrol sqeazy related tests just fine. I am on

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.5
BuildVersion:   16F73
```

**Comment by royerloic** [comment]
I have:

ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1510

but it fails :-(

> On 11 Sep 2017, at 13:14, Peter Steinbach <notifications@github.com> wrote:
> 
> sw_vers

Dr.  Loïc Alain Royer

Post-Doc - Myers Lab
Max Planck Institute
of Molecular Cell Biology
and Genetics
Pfotenhauerstr. 108
01307 Dresden

Too short? Here's why: http://emailcharter.org/

**Pull request merged**
